import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ClerkProvider, Show, UserButton } from "@clerk/nextjs";
import { AuthButtons } from "@/components/auth-buttons";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const clerkTheme = {
  variables: {
    colorPrimary: "#0ea5e9",
    colorBackground: "#0f172a",
    colorText: "#f1f5f9",
    colorNeutral: "#475569",
    colorInputBackground: "#1e293b",
    colorInputBorder: "#334155",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased dark`}
    >
      <body className="min-h-full flex flex-col bg-black text-white">
        <ClerkProvider appearance={{ baseTheme: clerkTheme }}>
          <header className="border-b border-gray-800">
            <div className="max-w-7xl mx-auto px-4 py-4 flex justify-between items-center">
              <h1 className="text-2xl font-bold">Link Shortener</h1>
              <div className="flex gap-4">
                <Show when="signed-out">
                  <AuthButtons />
                </Show>
                <Show when="signed-in">
                  <UserButton />
                </Show>
              </div>
            </div>
          </header>
          {children}
        </ClerkProvider>
      </body>
    </html>
  );
}
